### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by zloirock** [ljharb/proposal-dataview-get-set-uint8c#2]
Why `C` instead of `Clamped`? It's inconsistency with the name of the array constructor.

**Comment by ljharb** [comment]
That's the "type" value used in the spec's table. If we changed the type from "Uint8C" to "Uint8Clamped" everywhere, then the method name would follow suit.

**Comment by zloirock** [comment]
The spec has many internal names that make no sense open to users. Users know `Uint8Clamped`, it's strange to add `Uint8C` for the same.

**Comment by bakkot** [comment]
Yeah, spec-internal names should have exactly zero bearing on the names of user-exposed methods.

**Comment by ljharb** [comment]
→ https://github.com/tc39/ecma262/pull/3105
